# Generated by Django 3.2.8 on 2021-10-22 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgshop', '0002_image_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
    ]
