# Generated by Django 3.2.8 on 2021-10-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgshop', '0004_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='likes',
            new_name='likess',
        ),
    ]
