# Generated by Django 3.2.8 on 2021-10-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgshop', '0005_rename_likes_likess'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='like',
            field=models.IntegerField(null=True),
        ),
    ]
